config/routes.rb
Shouter::Application.routes.draw do
  root to: 'homes#show', via: :get
  resource :dashboard, only: [:show]

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:index, :new, :create, :show] do
  	post 'follow' => 'following_relationships#create'
  	delete 'follow' => 'following_relationships#destroy'
  end

  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]

end

app/models/concerns/following.rb
module Concerns
	module Following
		extend ActiveSupport::Concern

		included do
			has_many :followed_user_relationships, 
							foreign_key: :follower_id,
							class_name: 'FollowingRelationship'
			has_many :followed_users, through: :followed_user_relationships

			has_many :follower_relationships, 
							foreign_key: :followed_user_id,
							class_name: 'FollowingRelationship'
			has_many :followers, through: :follower_relationships
		end

		def following?(user)
			followed_user_ids.include? user.id
		end

		def follow(user)
			followed_users << user	
		end
		def unfollow(user)
			followed_users.delete user	
		end
	end
end

app/models/dashboard.rb
class Dashboard
	def initialize(user)
		@user = user
	end

	def new_text_shout
		TextShout.new
	end

	def new_photo_shout
		PhotoShout.new
	end

	def timeline
		Timeline.new(@user)
	end
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed_user, class_name: 'User'
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
	has_attached_file :image, styles: {
		shout: "400X400>"
	}
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user

  default_scope {order("created_at DESC")}

  belongs_to :content, polymorphic: true
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
  attr_accessible :body
end

app/models/timeline.rb
class Timeline
	extend ActiveModel::Naming
	def initialize(user)
		@user = user
	end

	def shouts
		Shout.where(user_id: shout_user_ids)
	end


	private

	def shout_user_ids
		@user.followed_user_ids + [@user.id]
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	include Concerns::Following

	has_many :shouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def show
		@dashboard = Dashboard.new(current_user)
	end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
	def create
		current_user.follow user
		redirect_to user, notice: 'Now following user.'
	end

	def destroy
		current_user.unfollow user
		redirect_to user, notice: 'No longer following user.'
	end

	private

	def user
		@_user ||= User.find(params[:user_id])
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_filter :check_logged_in_user
	def show
		
	end


	private

	def check_logged_in_user
		if signed_in?
			redirect_to dashboard_path
		end
	end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController
		def create
		content = build_content
		shout = current_user.shouts.build(content: content)
		
		flash.alert = "Could not shout" unless shout.save
		redirect_to dashboard_path
	end


	private

	def build_content
		PhotoShout.new(photo_shout_params)
	end

	def photo_shout_params
		params.require(:photo_shout).permit(:image)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :html

  def new
  end

  def create
    user = authenticate_session(session_params)
    sign_in(user) or set_flash_message
    respond_with user, location: root_path
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def set_flash_message
    flash.now.notice = "Invalid username or password"
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController

	def show
		@shout = Shout.find(params[:id])
	end

end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
	def create
		content = build_content
		shout = current_user.shouts.build(content: content)
		
		flash.alert = "Could not shout" unless shout.save
		redirect_to dashboard_path
	end


	private

	def build_content
		TextShout.new(text_shout_params)
	end

	def text_shout_params
		params.require(:text_shout).permit(:body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)
    sign_in(@user)
    respond_with @user, location: root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shouts_helper.rb
require "digest/md5"
module ShoutsHelper
	def gravatar(user, size = 48, options = {})
		digest = Digest::MD5.hexdigest(user.email)
		url = "http://gravatar.com/avatar/#{digest}?s=#{size}"
		image_tag(url, options)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def follow_button user
		if current_user == user
			return
		elsif current_user.following? user
			button_to "Unfollow", user_follow_path(user), 
													method: :delete,
													class:"btn btn-danger"
		else
			button_to "Follow", user_follow_path(user), class:"btn btn-success"
		end
	end
end

app/views/dashboards/_new_photo_shout_form.html.erb
<%= form_for @dashboard.new_photo_shout, html: {class: 'form-inline', role: 'form'} do |form| %>
	<div class="input-group">
		<%= form.file_field :image, class:"form-control"%>
		<span class="input-group-btn">
			<%= form.submit 'Shout!!!', class: "btn btn-default" %>
		</span>
	</div>
<% end %>

app/views/dashboards/_new_text_shout_form.html.erb
<%= form_for @dashboard.new_text_shout, html: {class: 'form-inline', role: 'form'} do |form| %>
	<div class="input-group">
		<%= form.text_field :body, class:"form-control", placeholder: 'Shout text here' %>
		<span class="input-group-btn">
			<%= form.submit 'Shout!!!', class: "btn btn-default" %>
		</span>
	</div>
<% end %>

app/views/dashboards/show.html.erb
<div class="row">
	<div class="page-header">
	  <h1>Dashboard <small><%= current_user.email %></small></h1>
	</div>
</div>
<div class="row shout-form">
	<div class="col col-sm-6">
		<%= render 'new_text_shout_form' %>
	</div>

	<div class="col col-sm-6">
		<%= render 'new_photo_shout_form' %>
	</div>
</div>

<%= render @dashboard.timeline %>

app/views/homes/show.html.erb
<div class="row">
	<div class="col col-md-6 col-md-offset-3 page-header">
		<h1>
			Welcome to Shouter
			<small>Sign in</small>
		</h1>
	</div>
</div>
<div class="row">
	<div class="col col-md-6 col-md-offset-3">
		<div class="sign-in-form">
			<%= render "sessions/form" %>
		</div>
		<p>
			<span class="pull-right">
			Have an account
			<%= link_to "Sign up here", new_user_path %>
			</span>
		</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="navbar navbar-fixed-top navbar-inverse">
		<% if signed_in? %>
			<%= link_to current_user.username, dashboard_path, class:"navbar-brand" %>
			<ul class="nav navbar-nav nav-pills">
				<li>
					<%= link_to 'Sign out', session_path, method: :delete %>
				</li>
		<% else %>
			<%= link_to "SHOUTER", root_path, class:"navbar-brand" %>
			<ul class="nav navbar-nav nav-pills">
				<li>
					<%= link_to 'Sign in', new_session_path %>
				</li>
				<li>
					<%= link_to 'Sign up', new_user_path %>
				</li>
		<% end %>
			<li><%= link_to "Users", users_path %></li>
		</ul>
	</div>
	<% if alert %>
		<div class="row">
			<div class="alert alert-danger"><%= alert %></div>
		</div>
	<% end %>
	<% if notice %>
		<div class="row">
			<div class="alert alert-warning"><%= notice %></div>
		</div>
	<% end %>
	<%= yield %>
</div>

</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= link_to image_tag(
	photo_shout.image.url(:shout), 
	class:"img-responsive img-rounded"), photo_shout.image.url %>

app/views/shouts/_shout.html.erb
<div class="row shout">
	<div class="avatar col col-md-1 col-xs-2">
		<%= gravatar(shout.user, 
									48, 
									class: "img-responsive img-thumbnail")  %>
		
	</div>
	<div class="content col col-md-11 col-xs-10">
		<blockquote>
			<header>
				<span class="glyphicon glyphicon-user"></span>
				<%= link_to shout.user.username, shout.user %> shouted 
				<%= link_to time_ago_in_words(shout.created_at), shout %> ago.
			</header>
			<p><%= render shout.content %></p>
		</blockquote>
	</div>
</div>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/timelines/_timeline.html.erb
<div class="timeline">
	<%= render timeline.shouts %>
</div>

app/views/users/_user.html.erb
<%= gravatar user, 30 %>
<%= link_to user.username, user %>
<span class="badge">
	<%= pluralize user.followers.size, "Follower" %>
</span>
<span class="badge">
	<%= pluralize user.shouts.size, "Shout" %>
</span>

app/views/users/index.html.erb
<div class="page-header">
	<h1>All Users</h1>
</div>

<ul class="list-group">
	<% @users.each do |user| %>
		<li class="list-group-item">
			<%= render user %>
		</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user, html: {role: 'form'} do |form| %>
  <div class="form-group form-field">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control" %>
  </div>
  <div class="form-group form-field">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group form-field">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div>
    <%= form.submit "Sign up",class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
	<div class="row">
		
		<div class="col col-md-2 col-xs-4">
			<%= gravatar(@user, 150) %>
		</div>
		<div class="col col-md-10 col-xs-8">
			<div class="row">
				<h1 class="col col-xs-12">
					<%= @user.username %>
					<small>
						<%= @user.email %>
					</small>
				</h1>
			</div>
			<div class="row">
				<div class="col col-xs-12">
					<%= follow_button @user %>
				</div>
			</div>
		</div>

	</div>
</div>

<%= render @user.shouts %>